import Head from 'next/head'
// import Image from 'next/image'
import {
  useSession, signIn, signOut
} from 'next-auth/client'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [session, loading] = useSession()
  if(session) {
    return (
      <>
        Signed in as {session.user.email} <br/>
        <button onClick={()=> signOut()}>Sign out</button>
      </>
    )
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <main className={styles.main}>
      <p>Not signed in </p>
        <h1 className={styles.title}>
          Welcome to Talking Drum!
        </h1>
        <button onClick={() => signIn()}>Sign in</button>
      </main>

      
    </div>
  )
}
